# Site settings
title: Hibah Gigih
email: Hibahgigih@gmail.com
url: https://hibahgigih.github.io
description: "Jalani - Nikmati - Syukuri"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: hibahgigih.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hibahgigih
  - title: facebook
    url: https://www.facebook.com/hibah.outsiders
  - title: google-plus
    url: https://plus.google.com/+HibahGigih
  - title: instagram
    url: http://instagram.com
  - title: github
    url: https://github.com/hibahgigih

# Build settings
markdown: kramdown
permalink: pretty
